#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Bootstrap Laravel Application
|--------------------------------------------------------------------------
|
| Load the Laravel application instance and execute the console command.
|
*/

$app = require_once __DIR__ . '/bootstrap/app.php';


$status = $app->handleCommand(new ArgvInput());


exit($status);